### ISSUE TITLE
Saving Overlay Position

### ISSUE THREAD

**Issue by Puppies-On-Acid** [algernon-A/ImageOverlayLite#1]
When resizing an overlay and moving it to a certain area of the map, the location of the overlay is not saved when the game is saved and reloaded later.

**Comment by algernon-A** [comment]
So you'd like to save the previous position?

**Comment by Puppies-On-Acid** [comment]
> So you'd like to save the previous position?

Yeah, that would be awesome! 

Also, being able to move the overlay a little quicker would be nice too. Or if you could just hold down CTRL/shift+arrow key instead of having to tap the arrow key over and over.

**Comment by GIS-PuppetMaster** [comment]
> So you'd like to save the previous position?那么您想保存之前的位置吗？

Also, I hope I can edit the scale, offset (position) within a config file, so that when the saved value is lost accidentally, or I play two map with different offset, I can set it back to the accuracy value

**Comment by algernon-A** [comment]
Closing as this version of the mod is deprecated and has been replaced by the version on Paradox Mods.
